# GENERATED by Scripts/generate-sdks.sh from Schema/siriusmsg-protocol-v1.schema.json. Do not edit.

from __future__ import annotations

from enum import Enum
from typing import Literal, Optional

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel, conint, constr


class SiriusMsgAccessibilityPermission(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    checkedAt: float = Field(
        ...,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    isTrusted: bool
    process: SiriusMsgProcessIdentity


class SiriusMsgActivityRecord(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    chatReference: Optional[str] = None
    connectionID: Optional[str] = None
    id: str
    needsAttention: bool
    result: str
    symbol: str
    timestamp: float = Field(
        ...,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    title: str


class SiriusMsgAdapterID(RootModel[str]):
    root: str = Field(..., description='Adapter identifier.')


class SiriusMsgAdapterMaintenanceResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    adapterID: SiriusMsgAdapterID
    clearedBlockedReviewJobs: int
    queueMetrics: SiriusMsgAdapterQueueMetrics


class SiriusMsgAdapterMode(Enum):
    direct = 'direct'
    durable = 'durable'


class SiriusMsgAdapterQueueMetrics(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    blockedReview: int
    deadLetter: int
    failed: int
    oldestPendingJobAgeSeconds: Optional[float] = None
    processing: int
    queued: int
    retrying: int
    succeeded: int


class SiriusMsgAdapterRunState(Enum):
    backingOff = 'backingOff'
    blocked = 'blocked'
    connecting = 'connecting'
    failed = 'failed'
    idle = 'idle'
    processing = 'processing'
    stopped = 'stopped'
    subscribed = 'subscribed'


class SiriusMsgAdapterStatus(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    activeMessageID: Optional[SiriusMsgMessageID] = None
    adapterID: SiriusMsgAdapterID
    connectionID: Optional[str] = None
    diagnostic: str
    lastSuccessfulTurnAt: Optional[float] = Field(
        None,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    mode: SiriusMsgAdapterMode
    queueMetrics: SiriusMsgAdapterQueueMetrics
    runState: SiriusMsgAdapterRunState
    updatedAt: float = Field(
        ...,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )


class SiriusMsgAgentConnection(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agentID: SiriusMsgAgentID
    agentName: Optional[str] = None
    executableURL: AnyUrl
    projectDirectory: AnyUrl


class SiriusMsgAgentControlCommand(Enum):
    beginSleepWakeCheckpoint = 'beginSleepWakeCheckpoint'
    beginValidationRun = 'beginValidationRun'
    clearAdapterReview = 'clearAdapterReview'
    completeSleepWakeCheckpoint = 'completeSleepWakeCheckpoint'
    createConnection = 'createConnection'
    diagnoseOutboundAttachmentRows = 'diagnoseOutboundAttachmentRows'
    enableAndExportVMAccess = 'enableAndExportVMAccess'
    finishValidationRun = 'finishValidationRun'
    listAllowlistCandidates = 'listAllowlistCandidates'
    listChats = 'listChats'
    probeAccessibility = 'probeAccessibility'
    probeAutomation = 'probeAutomation'
    probeFullDiskAccess = 'probeFullDiskAccess'
    probeVMAccess = 'probeVMAccess'
    readActivity = 'readActivity'
    readConfiguration = 'readConfiguration'
    reloadRecipes = 'reloadRecipes'
    removeConnection = 'removeConnection'
    runCapabilityHonestySmoke = 'runCapabilityHonestySmoke'
    runMessagesRestartCheckpoint = 'runMessagesRestartCheckpoint'
    runServiceRestartCheckpoint = 'runServiceRestartCheckpoint'
    runSubscriberReconnectCheckpoint = 'runSubscriberReconnectCheckpoint'
    savePythonAdapterConfiguration = 'savePythonAdapterConfiguration'
    sendAutomationSmoke = 'sendAutomationSmoke'
    sendOutboundFileSmoke = 'sendOutboundFileSmoke'
    sendRichLinkSmoke = 'sendRichLinkSmoke'
    setActivityRetention = 'setActivityRetention'
    setRichMessagingConfiguration = 'setRichMessagingConfiguration'
    setVMAccessEnabled = 'setVMAccessEnabled'
    shutdown = 'shutdown'
    status = 'status'
    updateConnection = 'updateConnection'


class SiriusMsgAgentControlRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    accountID: Optional[str] = None
    activityRetentionDays: Optional[int] = None
    adapterID: Optional[SiriusMsgAdapterID] = None
    appProcess: Optional[SiriusMsgProcessIdentity] = None
    attachmentFileURL: Optional[AnyUrl] = None
    chatID: Optional[SiriusMsgChatID] = None
    chatListQuery: Optional[SiriusMsgChatListQuery] = None
    command: SiriusMsgAgentControlCommand
    connectionID: Optional[str] = None
    connectionProfile: Optional[SiriusMsgConnectionProfile] = None
    exportURL: Optional[AnyUrl] = None
    messageText: Optional[str] = None
    privacySentinel: Optional[str] = None
    pythonAdapterConfiguration: Optional[SiriusMsgPythonAdapterConfiguration] = None
    richLinkCardsBaseURL: Optional[AnyUrl] = None
    richLinkImageURL: Optional[AnyUrl] = None
    richLinkTitle: Optional[str] = None
    richLinkURL: Optional[AnyUrl] = None
    richMessagingConfiguration: Optional[SiriusMsgRichMessagingConfiguration] = None
    validationRunID: Optional[str] = None
    vmAccessEnabled: Optional[bool] = None


class SiriusMsgAgentControlResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    accepted: bool
    accessibilityPermission: Optional[SiriusMsgAccessibilityPermission] = None
    activityRecords: Optional[list[SiriusMsgActivityRecord]] = None
    adapterMaintenanceResult: Optional[SiriusMsgAdapterMaintenanceResult] = None
    adapterStatuses: Optional[list[SiriusMsgAdapterStatus]] = None
    allowlistCandidates: list[SiriusMsgAllowlistCandidate]
    chatListPage: Optional[SiriusMsgChatListPage] = None
    configuration: Optional[SiriusMsgLocalConfigurationSnapshot] = None
    connectionProfile: Optional[SiriusMsgConnectionProfile] = None
    error: Optional[str] = None
    health: Optional[SiriusMsgHealth] = None
    restartRequired: Optional[bool] = None
    status: Optional[SiriusMsgAgentRuntimeStatus] = None
    validationResult: Optional[SiriusMsgValidationResult] = None
    validationRun: Optional[SiriusMsgValidationRun] = None
    validationRuns: Optional[list[SiriusMsgValidationRun]] = None
    vmGuestConfiguration: Optional[SiriusMsgVMGuestConfiguration] = None


class SiriusMsgAgentID(Enum):
    claude = 'claude'
    codex = 'codex'
    deepseek = 'deepseek'
    hermes = 'hermes'
    openclaw = 'openclaw'
    opencode = 'opencode'
    pi = 'pi'
    sirius = 'sirius'


class SiriusMsgAgentRuntimeStatus(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    controlSocketPath: str
    lastHealth: SiriusMsgHealth
    process: SiriusMsgProcessIdentity
    runtimeFiles: list[SiriusMsgRuntimeFileIdentity]
    serviceSocketPath: str
    signing: SiriusMsgCodeSigningIdentity
    startedAt: float = Field(
        ...,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    updatedAt: float = Field(
        ...,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )


class SiriusMsgAllowedChatQuery(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    limit: conint(ge=1, le=100)
    searchText: Optional[constr(max_length=1024)] = None


class SiriusMsgAllowlist(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    chatIDs: list[SiriusMsgChatID]
    handleIDs: list[SiriusMsgHandleID]
    replyDeniedChatIDs: Optional[list[SiriusMsgChatID]] = None


class SiriusMsgAllowlistCandidate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    chatID: SiriusMsgChatID
    displayName: Optional[str] = None
    identifier: Optional[str] = None
    lastActivityAt: Optional[float] = Field(
        None,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    lastRowID: Optional[conint(ge=0, le=9007199254740991)] = Field(
        None,
        description='Int64 ROWID constrained to the JavaScript safe-integer range for generated SDKs.',
    )
    participantCount: conint(ge=0)
    serviceName: Optional[str] = None


class SiriusMsgAttachmentDiagnosticCode(Enum):
    attachmentCapableSubscriberRequired = 'attachmentCapableSubscriberRequired'
    failedTranscode = 'failedTranscode'
    sourceOutsideMessagesAttachments = 'sourceOutsideMessagesAttachments'
    tooLarge = 'tooLarge'
    unreadable = 'unreadable'
    unsupportedType = 'unsupportedType'


class SiriusMsgAttachmentFetchRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attachmentID: SiriusMsgAttachmentID


class SiriusMsgAttachmentFileReference(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    localFilePath: str
    metadata: SiriusMsgAttachmentMetadata


class SiriusMsgAttachmentID(RootModel[str]):
    root: str = Field(..., description='Public attachment identifier.')


class SiriusMsgAttachmentKind(Enum):
    document = 'document'
    image = 'image'


class SiriusMsgAttachmentMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    byteCount: int
    diagnosticCode: Optional[SiriusMsgAttachmentDiagnosticCode] = None
    displayName: Optional[str] = None
    height: Optional[int] = None
    id: SiriusMsgAttachmentID
    kind: SiriusMsgAttachmentKind
    mimeType: str
    sha256: Optional[str] = None
    state: SiriusMsgAttachmentState
    width: Optional[int] = None


class SiriusMsgAttachmentState(Enum):
    failed = 'failed'
    materialized = 'materialized'
    tooLarge = 'tooLarge'
    unreadable = 'unreadable'
    unsupportedType = 'unsupportedType'


class SiriusMsgAuthTokenRotationResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    createdAt: float = Field(
        ...,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    previousCreatedAt: float = Field(
        ...,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    rotatedAt: float = Field(
        ...,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    staleAfterDays: int
    token: str
    vmExportsRefreshed: Optional[bool] = None


class SiriusMsgCapability(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    diagnosticCode: Optional[str] = None
    evidenceNote: str
    evidenceURL: Optional[AnyUrl] = None
    feature: SiriusMsgFeature
    proof: SiriusMsgCapabilityProof
    support: SiriusMsgCapabilitySupport
    transport: SiriusMsgTransport


class SiriusMsgCapabilityProof(Enum):
    documented = 'documented'
    none = 'none'
    providerDocumented = 'providerDocumented'
    scriptingBridgeVerb = 'scriptingBridgeVerb'
    scriptingBridgeVerbAndDocumented = 'scriptingBridgeVerbAndDocumented'
    scriptingBridgeVerbAndStoreConfirmed = 'scriptingBridgeVerbAndStoreConfirmed'
    storeConfirmed = 'storeConfirmed'


class SiriusMsgCapabilitySupport(Enum):
    blocked = 'blocked'
    degraded = 'degraded'
    providerOnly = 'providerOnly'
    receiveOnly = 'receiveOnly'
    researchGated = 'researchGated'
    supported = 'supported'
    unsupported = 'unsupported'


class SiriusMsgChatID(RootModel[str]):
    root: str = Field(..., description='Public chat identifier.')


class SiriusMsgChatKindFilter(Enum):
    all = 'all'
    direct = 'direct'
    group = 'group'


class SiriusMsgChatListPage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    chats: list[SiriusMsgAllowlistCandidate]
    nextCursor: Optional[SiriusMsgChatPageCursor] = None


class SiriusMsgChatListQuery(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ascending: bool
    cursor: Optional[SiriusMsgChatPageCursor] = None
    kind: SiriusMsgChatKindFilter
    limit: int
    searchText: Optional[str] = None
    sort: SiriusMsgChatSort


class SiriusMsgChatPageCursor(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    chatRowID: int
    sortValue: str


class SiriusMsgChatSort(Enum):
    lastActivity = 'lastActivity'
    name = 'name'
    people = 'people'
    service = 'service'


class SiriusMsgCodeSigningIdentity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    authorities: list[str]
    diagnostic: str
    signingIdentifier: Optional[str] = None
    teamIdentifier: Optional[str] = None
    validationState: SiriusMsgCodeSigningValidationState


class SiriusMsgCodeSigningValidationState(Enum):
    adHoc = 'adHoc'
    invalid = 'invalid'
    unavailable = 'unavailable'
    unsigned = 'unsigned'
    valid = 'valid'
    wrongAuthority = 'wrongAuthority'
    wrongIdentifier = 'wrongIdentifier'
    wrongTeam = 'wrongTeam'


class SiriusMsgCodexConnection(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    executableURL: AnyUrl
    managedServerDirectory: Optional[AnyUrl] = None
    projectDirectory: Optional[AnyUrl] = None
    socketURL: AnyUrl
    threadID: str
    transcriptScope: Optional[SiriusMsgTranscriptScope] = None


class SiriusMsgConnectionProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agent: Optional[SiriusMsgAgentConnection] = None
    clientID: Optional[SiriusMsgAgentID] = None
    clientKind: Optional[str] = None
    codex: Optional[SiriusMsgCodexConnection] = None
    createdAt: float = Field(
        ...,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    displayName: str
    enabled: bool
    excludedChatIDs: list[SiriusMsgChatID]
    id: str
    includedChatIDs: Optional[list[SiriusMsgChatID]] = None
    incomingAllowed: bool
    repliesAllowed: bool
    setupConfigurationBackupURL: Optional[AnyUrl] = None
    setupConfigurationURL: Optional[AnyUrl] = None


class SiriusMsgContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attachment: Optional[SiriusMsgOutboundAttachment] = None
    edit: Optional[SiriusMsgEditContent] = None
    kind: SiriusMsgContentKind
    messageEffect: Optional[SiriusMsgMessageEffectContent] = None
    reaction: Optional[SiriusMsgReactionContent] = None
    reply: Optional[SiriusMsgReplyContent] = None
    richLink: Optional[SiriusMsgRichLink] = None
    text: Optional[constr(max_length=4096)] = None
    typing: Optional[SiriusMsgTypingState] = None
    unsend: Optional[SiriusMsgUnsendContent] = None
    unsupported: Optional[SiriusMsgUnsupportedContent] = None


class SiriusMsgContentKind(Enum):
    attachment = 'attachment'
    edit = 'edit'
    messageEffect = 'messageEffect'
    reaction = 'reaction'
    reply = 'reply'
    richLink = 'richLink'
    text = 'text'
    typing = 'typing'
    unsend = 'unsend'
    unsupported = 'unsupported'


class SiriusMsgCursorState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    lastRowIDByChatID: dict[str, int]


class SiriusMsgDeliverableEventCapture(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    capturedAt: float = Field(
        ...,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    chatID: SiriusMsgChatID
    containsMessageBody: bool
    messageID: SiriusMsgMessageID
    messageText: Optional[str] = None
    rowID: int


class SiriusMsgEditContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    replacementText: str
    targetMessageID: SiriusMsgMessageID


class SiriusMsgFeature(Enum):
    applePayBusinessAction = 'applePayBusinessAction'
    inboundAttachment = 'inboundAttachment'
    inboundEdit = 'inboundEdit'
    inboundReaction = 'inboundReaction'
    inboundReplyReference = 'inboundReplyReference'
    inboundText = 'inboundText'
    inboundUnsend = 'inboundUnsend'
    miniAppCard = 'miniAppCard'
    sendEdit = 'sendEdit'
    sendFile = 'sendFile'
    sendMessageEffect = 'sendMessageEffect'
    sendReaction = 'sendReaction'
    sendRichLink = 'sendRichLink'
    sendText = 'sendText'
    sendThreadedReply = 'sendThreadedReply'
    sendTypingIndicator = 'sendTypingIndicator'
    sendUnsend = 'sendUnsend'


class SiriusMsgHandleID(RootModel[str]):
    root: str = Field(..., description='Public handle identifier.')


class SiriusMsgHealth(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    activeTransport: SiriusMsgTransport
    capabilities: list[SiriusMsgCapability]
    components: list[SiriusMsgHealthComponent]
    reason: str
    recipeRuntime: Optional[SiriusMsgRecipeRuntimeStatus] = None
    state: SiriusMsgHealthState


class SiriusMsgHealthComponent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    detail: Optional[SiriusMsgHealthComponentDetail] = None
    kind: SiriusMsgHealthComponentKind
    reason: str
    state: SiriusMsgHealthComponentState


class SiriusMsgHealthComponentDetail(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    adapterID: Optional[SiriusMsgAdapterID] = None
    adapterMode: Optional[SiriusMsgAdapterMode] = None
    adapterQueueMetrics: Optional[SiriusMsgAdapterQueueMetrics] = None
    adapterRunState: Optional[SiriusMsgAdapterRunState] = None
    endpoint: Optional[str] = None
    lastVMReachabilityProbeAt: Optional[float] = Field(
        None,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    peerCredentialPolicy: Optional[str] = None
    peerCredentialsEnforced: Optional[bool] = None
    port: Optional[conint(ge=0, le=65535)] = None
    richMessagingFeatures: Optional[list[str]] = None
    richMessagingRemediation: Optional[str] = None
    richMessagingState: Optional[str] = None
    tokenAgeDays: Optional[int] = None
    tokenAuthenticationAvailable: Optional[bool] = None
    tokenCreatedAt: Optional[float] = Field(
        None,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    tokenMaintenanceDue: Optional[bool] = None
    tokenRemediation: Optional[str] = None
    tokenStaleAfterDays: Optional[int] = None
    vmReachability: Optional[SiriusMsgVMReachabilityState] = None


class SiriusMsgHealthComponentKind(Enum):
    adapters = 'adapters'
    allowlistPersistence = 'allowlistPersistence'
    attachments = 'attachments'
    authToken = 'authToken'
    automation = 'automation'
    cursorPersistence = 'cursorPersistence'
    hooks = 'hooks'
    messagesDatabase = 'messagesDatabase'
    serviceLock = 'serviceLock'
    socket = 'socket'
    vmListener = 'vmListener'


class SiriusMsgHealthComponentState(Enum):
    blocked = 'blocked'
    degraded = 'degraded'
    healthy = 'healthy'
    notConfigured = 'notConfigured'


class SiriusMsgHealthState(Enum):
    blocked = 'blocked'
    degraded = 'degraded'
    healthy = 'healthy'
    starting = 'starting'
    stopped = 'stopped'


class SiriusMsgHistoryMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attachmentCount: conint(ge=0)
    authorDisplayName: str
    chatID: SiriusMsgChatID
    handleID: Optional[SiriusMsgHandleID] = None
    id: SiriusMsgMessageID
    isFromMe: bool
    isGroupChat: bool
    replyToMessageID: Optional[SiriusMsgMessageID] = None
    rowID: conint(ge=0, le=9007199254740991) = Field(
        ...,
        description='Int64 ROWID constrained to the JavaScript safe-integer range for generated SDKs.',
    )
    sentAt: float = Field(
        ...,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    text: str
    textTruncated: Optional[bool] = False


class SiriusMsgHistoryPage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    messages: list[SiriusMsgHistoryMessage]
    nextBeforeRowID: Optional[conint(ge=0, le=9007199254740991)] = Field(
        None,
        description='Int64 ROWID constrained to the JavaScript safe-integer range for generated SDKs.',
    )
    scannedRowCount: conint(ge=0)


class SiriusMsgHistoryReadRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    beforeRowID: Optional[conint(ge=0, le=9007199254740991)] = Field(
        None,
        description='Int64 ROWID constrained to the JavaScript safe-integer range for generated SDKs.',
    )
    chatID: SiriusMsgChatID
    limit: conint(ge=1, le=100)


class SiriusMsgHistorySearchRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    beforeRowID: Optional[conint(ge=0, le=9007199254740991)] = Field(
        None,
        description='Int64 ROWID constrained to the JavaScript safe-integer range for generated SDKs.',
    )
    chatIDs: Optional[list[SiriusMsgChatID]] = Field(None, max_length=20)
    limit: conint(ge=1, le=100)
    query: constr(max_length=1024)


class SiriusMsgImageRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mimeType: Optional[str] = None
    sha256: Optional[str] = None
    url: AnyUrl


class SiriusMsgInboundEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: SiriusMsgInboundEventKind
    message: Optional[SiriusMsgMessageEvent] = None
    messageEdited: Optional[SiriusMsgMessageEditedEvent] = None
    messageUnsent: Optional[SiriusMsgMessageUnsentEvent] = None
    reaction: Optional[SiriusMsgReactionEvent] = None
    replyReference: Optional[SiriusMsgReplyReferenceEvent] = None


class SiriusMsgInboundEventKind(Enum):
    message = 'message'
    messageEdited = 'messageEdited'
    messageUnsent = 'messageUnsent'
    reaction = 'reaction'
    replyReference = 'replyReference'


class SiriusMsgLocalConfigurationSnapshot(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    activityRetentionDays: int
    allowlist: SiriusMsgAllowlist
    connections: list[SiriusMsgConnectionProfile]
    pythonAdapters: list[SiriusMsgPythonAdapterConfiguration]
    richMessaging: Optional[SiriusMsgRichMessagingConfiguration] = None
    vmAccessEnabled: bool


class SiriusMsgMessageEditedEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    chatID: SiriusMsgChatID
    editedAt: float = Field(
        ...,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    isGroupChat: bool
    messageID: SiriusMsgMessageID
    rowID: conint(ge=0, le=9007199254740991) = Field(
        ...,
        description='Int64 ROWID constrained to the JavaScript safe-integer range for generated SDKs.',
    )


class SiriusMsgMessageEffectContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    effectName: str
    text: str


class SiriusMsgMessageEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attachments: list[SiriusMsgAttachmentMetadata]
    authorDisplayName: str
    chatID: SiriusMsgChatID
    handleID: Optional[SiriusMsgHandleID] = None
    id: SiriusMsgMessageID
    isGroupChat: bool
    receivedAt: float = Field(
        ...,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    replyToMessageID: Optional[SiriusMsgMessageID] = None
    rowID: conint(ge=0, le=9007199254740991) = Field(
        ...,
        description='Int64 ROWID constrained to the JavaScript safe-integer range for generated SDKs.',
    )
    text: str


class SiriusMsgMessageID(RootModel[str]):
    root: str = Field(..., description='Public message identifier.')


class SiriusMsgMessageUnsentEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    chatID: SiriusMsgChatID
    isGroupChat: bool
    messageID: SiriusMsgMessageID
    retractedAt: float = Field(
        ...,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    rowID: conint(ge=0, le=9007199254740991) = Field(
        ...,
        description='Int64 ROWID constrained to the JavaScript safe-integer range for generated SDKs.',
    )


class SiriusMsgMessagingValidationEvidence(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attachmentByteCount: Optional[int] = None
    attachmentMIMEType: Optional[str] = None
    attachmentSHA256: Optional[str] = None
    capabilityDiagnostics: list[str]
    confirmationState: Optional[SiriusMsgSendConfirmationState] = None
    contentKind: SiriusMsgContentKind
    diagnostics: list[str]
    generatedPreviewRequested: bool
    platformMessageID: Optional[str] = None
    providerTransportsQueried: list[SiriusMsgTransport]
    resolvedRichLinkURL: Optional[AnyUrl] = None
    richLinkURL: Optional[AnyUrl] = None


class SiriusMsgOutboundAttachment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    byteCount: int
    displayName: Optional[str] = None
    fileURL: AnyUrl
    mimeType: str
    sha256: str


class SiriusMsgProcessIdentity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    bundleIdentifier: Optional[str] = None
    effectiveUserID: int
    executablePath: str
    processIdentifier: int
    userID: int


class SiriusMsgPythonAdapterConfiguration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    adapterID: SiriusMsgAdapterID
    enabled: bool
    handlerFunction: str
    handlerModule: str
    includeMessageBody: bool
    pythonPackagePath: str
    supportsAttachments: bool
    timeoutSeconds: float
    workerCount: int


class SiriusMsgReaction(Enum):
    dislike = 'dislike'
    emphasize = 'emphasize'
    laugh = 'laugh'
    like = 'like'
    love = 'love'
    question = 'question'


class SiriusMsgReactionAction(Enum):
    added = 'added'
    removed = 'removed'


class SiriusMsgReactionContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action: SiriusMsgReactionAction
    reaction: SiriusMsgReaction
    targetMessageID: SiriusMsgMessageID


class SiriusMsgReactionEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action: SiriusMsgReactionAction
    authorDisplayName: str
    chatID: SiriusMsgChatID
    handleID: Optional[SiriusMsgHandleID] = None
    id: SiriusMsgMessageID
    isGroupChat: bool
    reaction: SiriusMsgReaction
    receivedAt: float = Field(
        ...,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    rowID: conint(ge=0, le=9007199254740991) = Field(
        ...,
        description='Int64 ROWID constrained to the JavaScript safe-integer range for generated SDKs.',
    )
    targetMessageID: SiriusMsgMessageID


class SiriusMsgRecipe(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    actions: list[SiriusMsgContent]
    description: str
    enabled: bool
    id: str
    integration: SiriusMsgRecipeIntegration
    name: str
    requiredCapabilities: list[SiriusMsgFeature]
    trigger: SiriusMsgRecipeTrigger


class SiriusMsgRecipeAdapterEnvelope(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    recipe: SiriusMsgRecipeIntegrationEnvelope
    triggerEvent: SiriusMsgRecipeTriggerEvent


class SiriusMsgRecipeIntegration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    identifier: Optional[str] = None
    kind: SiriusMsgRecipeIntegrationKind


class SiriusMsgRecipeIntegrationEnvelope(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    actionKinds: list[SiriusMsgContentKind]
    integration: SiriusMsgRecipeIntegration
    recipeID: str
    recipeName: str
    requiredCapabilities: list[SiriusMsgFeature]
    trigger: SiriusMsgRecipeTrigger


class SiriusMsgRecipeIntegrationKind(Enum):
    calendar = 'calendar'
    github = 'github'
    gmail = 'gmail'
    linear = 'linear'
    mcp = 'mcp'
    notion = 'notion'
    outlook = 'outlook'
    reminders = 'reminders'
    webhook = 'webhook'


class SiriusMsgRecipeRuntimeStatus(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    actionlessEnabledRecipeCount: int
    deferredTriggerRecipeCount: int
    diagnosticCounts: dict[str, int]
    enabledRecipeCount: int
    evaluatedCount: int
    failedCount: int
    lastEventAt: Optional[float] = Field(
        None,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    lastReloadAt: Optional[float] = Field(
        None,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    lastReloadDiagnostic: Optional[str] = None
    liveTriggers: list[SiriusMsgRecipeTrigger]
    loadedRecipeCount: int
    runningRecipeCount: int
    sentCount: int
    skippedCount: int
    triggerCounts: dict[str, SiriusMsgRecipeTriggerRuntimeCounts]


class SiriusMsgRecipeTrigger(Enum):
    edit = 'edit'
    inboundMessage = 'inboundMessage'
    reaction = 'reaction'
    schedule = 'schedule'
    unsend = 'unsend'
    webhook = 'webhook'


class SiriusMsgRecipeTriggerEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    chatID: SiriusMsgChatID
    handleID: Optional[SiriusMsgHandleID] = None
    isBridgeGenerated: bool
    messageID: Optional[SiriusMsgMessageID] = None
    rowID: Optional[conint(ge=0, le=9007199254740991)] = Field(
        None,
        description='Int64 ROWID constrained to the JavaScript safe-integer range for generated SDKs.',
    )
    source: SiriusMsgRecipeTriggerSource
    trigger: SiriusMsgRecipeTrigger


class SiriusMsgRecipeTriggerRuntimeCounts(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    diagnosticCounts: dict[str, int]
    evaluatedCount: int
    failedCount: int
    sentCount: int
    skippedCount: int


class SiriusMsgRecipeTriggerSource(Enum):
    inbound = 'inbound'
    schedule = 'schedule'
    webhook = 'webhook'


class SiriusMsgReconnectPolicy(Enum):
    default = 'default'
    none = 'none'


class SiriusMsgRecoveryValidationEvidence(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ackedEventSuppressed: bool
    ackOwnershipEnforced: bool
    afterHealthState: Optional[SiriusMsgHealthState] = None
    afterProcessIdentifier: Optional[int] = None
    automationRecovered: bool
    beforeHealthState: Optional[SiriusMsgHealthState] = None
    beforeProcessIdentifier: Optional[int] = None
    checkpoint: SiriusMsgValidationStep
    completedAt: float = Field(
        ...,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    cursorAdvancedOnlyAfterAck: bool
    diagnostics: list[str]
    duplicateAckRejected: bool
    fullDiskAccessRecovered: bool
    messageIDs: list[SiriusMsgMessageID]
    messagesApplicationRunning: bool
    rowIDs: list[int]
    socketAuthenticated: bool
    startedAt: float = Field(
        ...,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    statusHeartbeatRecovered: bool
    tokenReadable: bool
    tokenReused: bool
    unackedEventRedelivered: bool
    vmProbeRecovered: bool


class SiriusMsgReplyContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    targetMessageID: SiriusMsgMessageID
    text: str


class SiriusMsgReplyReferenceEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    chatID: SiriusMsgChatID
    isGroupChat: bool
    messageID: SiriusMsgMessageID
    receivedAt: float = Field(
        ...,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    repliedToMessageID: SiriusMsgMessageID
    rowID: conint(ge=0, le=9007199254740991) = Field(
        ...,
        description='Int64 ROWID constrained to the JavaScript safe-integer range for generated SDKs.',
    )


class SiriusMsgRichLink(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    imageRef: Optional[SiriusMsgImageRef] = None
    kind: SiriusMsgRichLinkKind
    subtitle: Optional[str] = None
    title: Optional[str] = None
    url: AnyUrl


class SiriusMsgRichLinkCardArtifact(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    html: str
    publicURL: AnyUrl
    redirectStatusCode: int
    redirectURL: AnyUrl
    slug: str


class SiriusMsgRichLinkKind(Enum):
    generatedPreview = 'generatedPreview'
    plain = 'plain'


class SiriusMsgRichMessagingConfiguration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    allowedFeatures: Optional[list[SiriusMsgFeature]] = None
    enabled: bool
    executablePath: str
    nativeEnabled: Optional[bool] = None
    provider: SiriusMsgRichMessagingProvider


class SiriusMsgRichMessagingProvider(Enum):
    imsg = 'imsg'
    nativeAccessibility = 'nativeAccessibility'


class SiriusMsgRuntimeFileIdentity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: SiriusMsgRuntimeFileKind
    mode: Optional[int] = None
    ownerUserID: Optional[int] = None
    path: str


class SiriusMsgRuntimeFileKind(Enum):
    directory = 'directory'
    missing = 'missing'
    other = 'other'
    regularFile = 'regularFile'
    socket = 'socket'
    symlink = 'symlink'


class SiriusMsgSchemaCapabilities(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    editAwarenessAvailable: bool
    replyReferenceAvailable: bool


class SiriusMsgSendConfirmationState(Enum):
    confirmed = 'confirmed'
    dispatched = 'dispatched'
    notRequested = 'notRequested'
    unconfirmed = 'unconfirmed'


class SiriusMsgSendRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    accountID: Optional[str] = None
    chatID: SiriusMsgChatID
    content: Optional[SiriusMsgContent] = None
    operationID: Optional[constr(max_length=128)] = None
    text: str


class SiriusMsgSendResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    accepted: bool
    confirmationState: SiriusMsgSendConfirmationState
    diagnosticCode: Optional[str] = None
    platformMessageID: Optional[str] = None
    resolvedContent: Optional[SiriusMsgContent] = None


class SiriusMsgServiceAck(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    chatID: SiriusMsgChatID
    messageID: SiriusMsgMessageID
    rowID: conint(ge=0, le=9007199254740991) = Field(
        ...,
        description='Int64 ROWID constrained to the JavaScript safe-integer range for generated SDKs.',
    )


class SiriusMsgServiceAuthToken(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    createdAt: float = Field(
        ...,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    token: str


class SiriusMsgServiceError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: SiriusMsgServiceErrorCode
    diagnosticCode: Optional[str] = None
    message: str


class SiriusMsgServiceErrorCode(Enum):
    ackNotOutstanding = 'ackNotOutstanding'
    attachmentHashMismatch = 'attachmentHashMismatch'
    attachmentNotDelivered = 'attachmentNotDelivered'
    attachmentNotFound = 'attachmentNotFound'
    attachmentTooLarge = 'attachmentTooLarge'
    attachmentTransportUnsupported = 'attachmentTransportUnsupported'
    attachmentUnavailable = 'attachmentUnavailable'
    attachmentUnsupportedType = 'attachmentUnsupportedType'
    authFailed = 'authFailed'
    authRequired = 'authRequired'
    backpressure = 'backpressure'
    historyUnavailable = 'historyUnavailable'
    internalError = 'internalError'
    invalidRequest = 'invalidRequest'
    malformedFrame = 'malformedFrame'
    peerCredentialsRejected = 'peerCredentialsRejected'
    protocolVersionUnsupported = 'protocolVersionUnsupported'
    sendOperationConflict = 'sendOperationConflict'
    sendOperationUnresolved = 'sendOperationUnresolved'
    sendRejected = 'sendRejected'
    subscriptionAlreadyActive = 'subscriptionAlreadyActive'
    tokenRotationFailed = 'tokenRotationFailed'
    transportUnavailable = 'transportUnavailable'


class SiriusMsgServiceEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    health: Optional[SiriusMsgHealth] = None
    kind: SiriusMsgServiceEventKind
    message: Optional[SiriusMsgMessageEvent] = None
    messageEdited: Optional[SiriusMsgMessageEditedEvent] = None
    messageUnsent: Optional[SiriusMsgMessageUnsentEvent] = None
    reaction: Optional[SiriusMsgReactionEvent] = None
    replyReference: Optional[SiriusMsgReplyReferenceEvent] = None


class SiriusMsgServiceEventKind(Enum):
    health = 'health'
    message = 'message'
    messageEdited = 'messageEdited'
    messageUnsent = 'messageUnsent'
    reaction = 'reaction'
    replyReference = 'replyReference'


class SiriusMsgServiceRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ack: Optional[SiriusMsgServiceAck] = None
    allowedChatQuery: Optional[SiriusMsgAllowedChatQuery] = None
    allowlist: Optional[SiriusMsgAllowlist] = None
    attachmentFetch: Optional[SiriusMsgAttachmentFetchRequest] = None
    authToken: Optional[str] = None
    historyRead: Optional[SiriusMsgHistoryReadRequest] = None
    historySearch: Optional[SiriusMsgHistorySearchRequest] = None
    kind: SiriusMsgServiceRequestKind
    protocolVersion: Literal[1] = Field(..., description='SiriusMsg protocol version.')
    requestID: str
    sendRequest: Optional[SiriusMsgSendRequest] = None
    subscriptionOptions: Optional[SiriusMsgSubscriptionOptions] = None
    transport: Optional[SiriusMsgTransport] = None


class SiriusMsgServiceRequestKind(Enum):
    ack = 'ack'
    authenticate = 'authenticate'
    capabilities = 'capabilities'
    fetchAttachment = 'fetchAttachment'
    health = 'health'
    listAllowedChats = 'listAllowedChats'
    readHistory = 'readHistory'
    rotateAuthToken = 'rotateAuthToken'
    searchHistory = 'searchHistory'
    send = 'send'
    subscribe = 'subscribe'
    updateAllowlist = 'updateAllowlist'


class SiriusMsgServiceResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    allowedChats: Optional[list[SiriusMsgAllowlistCandidate]] = None
    attachmentFile: Optional[SiriusMsgAttachmentFileReference] = None
    authTokenRotationResult: Optional[SiriusMsgAuthTokenRotationResult] = None
    capabilities: Optional[list[SiriusMsgCapability]] = None
    error: Optional[SiriusMsgServiceError] = None
    event: Optional[SiriusMsgServiceEvent] = None
    health: Optional[SiriusMsgHealth] = None
    historyPage: Optional[SiriusMsgHistoryPage] = None
    kind: SiriusMsgServiceResponseKind
    protocolVersion: Literal[1] = Field(..., description='SiriusMsg protocol version.')
    requestID: Optional[str] = None
    sendResult: Optional[SiriusMsgSendResult] = None


class SiriusMsgServiceResponseKind(Enum):
    acked = 'acked'
    allowedChats = 'allowedChats'
    allowlistUpdated = 'allowlistUpdated'
    attachmentFile = 'attachmentFile'
    authTokenRotated = 'authTokenRotated'
    authenticated = 'authenticated'
    capabilities = 'capabilities'
    error = 'error'
    event = 'event'
    health = 'health'
    historyPage = 'historyPage'
    sendResult = 'sendResult'
    subscribed = 'subscribed'


class SiriusMsgSubscriptionOptions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    supportsAttachments: bool


class SiriusMsgTranscriptScope(Enum):
    connection = 'connection'
    conversation = 'conversation'


class SiriusMsgTransport(Enum):
    localMessagesAutomation = 'localMessagesAutomation'
    managedRelay = 'managedRelay'
    messagesForBusiness = 'messagesForBusiness'


class SiriusMsgTransportDescriptor(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    displayName: str
    summary: str
    transport: SiriusMsgTransport
    trustPosture: SiriusMsgTransportTrustPosture


class SiriusMsgTransportTrustPosture(Enum):
    appleBusinessProvider = 'appleBusinessProvider'
    localMacPrivate = 'localMacPrivate'
    managedDedicatedRelay = 'managedDedicatedRelay'


class SiriusMsgTypingState(Enum):
    started = 'started'
    stopped = 'stopped'


class SiriusMsgUnsendContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    targetMessageID: SiriusMsgMessageID


class SiriusMsgUnsupportedContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    diagnosticCode: str
    feature: SiriusMsgFeature
    reason: str


class SiriusMsgVMGuestConfiguration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    authToken: str
    endpointHost: str
    endpointPort: int
    generatedAt: float = Field(
        ...,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    generatingBundleIdentifier: Optional[str] = None
    generatingTeamIdentifier: Optional[str] = None
    protocolVersion: int
    tokenCreatedAt: float = Field(
        ...,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    tokenStaleAfterDays: int


class SiriusMsgVMReachabilityState(Enum):
    reachable = 'reachable'
    unprobed = 'unprobed'
    unreachable = 'unreachable'


class SiriusMsgValidationResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    bundleIdentifier: Optional[str] = None
    deliverableEventCapture: Optional[SiriusMsgDeliverableEventCapture] = None
    diagnostic: str
    messagingEvidence: Optional[SiriusMsgMessagingValidationEvidence] = None
    process: SiriusMsgProcessIdentity
    recoveryEvidence: Optional[SiriusMsgRecoveryValidationEvidence] = None
    signing: SiriusMsgCodeSigningIdentity
    state: SiriusMsgValidationResultState
    step: SiriusMsgValidationStep
    teamIdentifier: Optional[str] = None
    timestamp: float = Field(
        ...,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )


class SiriusMsgValidationResultState(Enum):
    failed = 'failed'
    passed = 'passed'
    skipped = 'skipped'


class SiriusMsgValidationRun(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agentProcess: Optional[SiriusMsgProcessIdentity] = None
    appProcess: Optional[SiriusMsgProcessIdentity] = None
    appSigning: Optional[SiriusMsgCodeSigningIdentity] = None
    completedAt: Optional[float] = Field(
        None,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    id: str
    privacySentinel: Optional[str] = None
    results: list[SiriusMsgValidationResult]
    startedAt: float = Field(
        ...,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )


class SiriusMsgValidationStep(Enum):
    automationProbe = 'automationProbe'
    automationSendSmoke = 'automationSendSmoke'
    capabilityHonesty = 'capabilityHonesty'
    fullDiskAccessProbe = 'fullDiskAccessProbe'
    messagesRestart = 'messagesRestart'
    outboundAttachmentRows = 'outboundAttachmentRows'
    outboundFileSendSmoke = 'outboundFileSendSmoke'
    privacySentinel = 'privacySentinel'
    richLinkSmoke = 'richLinkSmoke'
    runtimeFiles = 'runtimeFiles'
    serviceRestart = 'serviceRestart'
    signedIdentity = 'signedIdentity'
    sleepWake = 'sleepWake'
    subscriberReconnect = 'subscriberReconnect'
    vmExport = 'vmExport'
    vmProbe = 'vmProbe'


class SiriusmsgProtocolV1(BaseModel):
    pass
