# GENERATED by Scripts/generate-sdks.sh from Schema/siriusmsg-protocol-v1.schema.json. Do not edit.

from __future__ import annotations

from enum import Enum
from typing import Literal, Optional

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel, conint


class SiriusMsgAdapterID(RootModel[str]):
    root: str = Field(..., description='Adapter identifier.')


class SiriusMsgAdapterMode(Enum):
    direct = 'direct'
    durable = 'durable'


class SiriusMsgAdapterQueueMetrics(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    blockedReview: int
    deadLetter: int
    failed: int
    oldestPendingJobAgeSeconds: Optional[float] = None
    processing: int
    queued: int
    retrying: int
    succeeded: int


class SiriusMsgAdapterRunState(Enum):
    backingOff = 'backingOff'
    blocked = 'blocked'
    connecting = 'connecting'
    failed = 'failed'
    idle = 'idle'
    processing = 'processing'
    stopped = 'stopped'
    subscribed = 'subscribed'


class SiriusMsgAllowlist(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    chatIDs: list[SiriusMsgChatID]
    handleIDs: list[SiriusMsgHandleID]


class SiriusMsgAttachmentDiagnosticCode(Enum):
    attachmentCapableSubscriberRequired = 'attachmentCapableSubscriberRequired'
    failedTranscode = 'failedTranscode'
    sourceOutsideMessagesAttachments = 'sourceOutsideMessagesAttachments'
    tooLarge = 'tooLarge'
    unreadable = 'unreadable'
    unsupportedType = 'unsupportedType'


class SiriusMsgAttachmentFetchRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attachmentID: SiriusMsgAttachmentID


class SiriusMsgAttachmentFileReference(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    localFilePath: str
    metadata: SiriusMsgAttachmentMetadata


class SiriusMsgAttachmentID(RootModel[str]):
    root: str = Field(..., description='Public attachment identifier.')


class SiriusMsgAttachmentKind(Enum):
    document = 'document'
    image = 'image'


class SiriusMsgAttachmentMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    byteCount: int
    diagnosticCode: Optional[SiriusMsgAttachmentDiagnosticCode] = None
    displayName: Optional[str] = None
    height: Optional[int] = None
    id: SiriusMsgAttachmentID
    kind: SiriusMsgAttachmentKind
    mimeType: str
    sha256: Optional[str] = None
    state: SiriusMsgAttachmentState
    width: Optional[int] = None


class SiriusMsgAttachmentState(Enum):
    failed = 'failed'
    materialized = 'materialized'
    tooLarge = 'tooLarge'
    unreadable = 'unreadable'
    unsupportedType = 'unsupportedType'


class SiriusMsgAuthTokenRotationResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    createdAt: float = Field(
        ...,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    previousCreatedAt: float = Field(
        ...,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    rotatedAt: float = Field(
        ...,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    staleAfterDays: int
    token: str


class SiriusMsgCapability(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    diagnosticCode: Optional[str] = None
    evidenceNote: str
    evidenceURL: Optional[AnyUrl] = None
    feature: SiriusMsgFeature
    proof: SiriusMsgCapabilityProof
    support: SiriusMsgCapabilitySupport
    transport: SiriusMsgTransport


class SiriusMsgCapabilityProof(Enum):
    documented = 'documented'
    none = 'none'
    providerDocumented = 'providerDocumented'
    scriptingBridgeVerb = 'scriptingBridgeVerb'
    scriptingBridgeVerbAndDocumented = 'scriptingBridgeVerbAndDocumented'
    scriptingBridgeVerbAndStoreConfirmed = 'scriptingBridgeVerbAndStoreConfirmed'
    storeConfirmed = 'storeConfirmed'


class SiriusMsgCapabilitySupport(Enum):
    blocked = 'blocked'
    degraded = 'degraded'
    providerOnly = 'providerOnly'
    receiveOnly = 'receiveOnly'
    researchGated = 'researchGated'
    supported = 'supported'
    unsupported = 'unsupported'


class SiriusMsgChatID(RootModel[str]):
    root: str = Field(..., description='Public chat identifier.')


class SiriusMsgContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attachment: Optional[SiriusMsgOutboundAttachment] = None
    edit: Optional[SiriusMsgEditContent] = None
    kind: SiriusMsgContentKind
    messageEffect: Optional[SiriusMsgMessageEffectContent] = None
    reaction: Optional[SiriusMsgReactionContent] = None
    reply: Optional[SiriusMsgReplyContent] = None
    richLink: Optional[SiriusMsgRichLink] = None
    text: Optional[str] = None
    typing: Optional[SiriusMsgTypingState] = None
    unsend: Optional[SiriusMsgUnsendContent] = None
    unsupported: Optional[SiriusMsgUnsupportedContent] = None


class SiriusMsgContentKind(Enum):
    attachment = 'attachment'
    edit = 'edit'
    messageEffect = 'messageEffect'
    reaction = 'reaction'
    reply = 'reply'
    richLink = 'richLink'
    text = 'text'
    typing = 'typing'
    unsend = 'unsend'
    unsupported = 'unsupported'


class SiriusMsgCursorState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    lastRowIDByChatID: dict[str, int]


class SiriusMsgEditContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    replacementText: str
    targetMessageID: SiriusMsgMessageID


class SiriusMsgFeature(Enum):
    applePayBusinessAction = 'applePayBusinessAction'
    inboundAttachment = 'inboundAttachment'
    inboundEdit = 'inboundEdit'
    inboundReaction = 'inboundReaction'
    inboundReplyReference = 'inboundReplyReference'
    inboundText = 'inboundText'
    inboundUnsend = 'inboundUnsend'
    miniAppCard = 'miniAppCard'
    sendEdit = 'sendEdit'
    sendFile = 'sendFile'
    sendMessageEffect = 'sendMessageEffect'
    sendReaction = 'sendReaction'
    sendRichLink = 'sendRichLink'
    sendText = 'sendText'
    sendThreadedReply = 'sendThreadedReply'
    sendTypingIndicator = 'sendTypingIndicator'
    sendUnsend = 'sendUnsend'


class SiriusMsgHandleID(RootModel[str]):
    root: str = Field(..., description='Public handle identifier.')


class SiriusMsgHealth(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    activeTransport: SiriusMsgTransport
    capabilities: list[SiriusMsgCapability]
    components: list[SiriusMsgHealthComponent]
    reason: str
    recipeRuntime: Optional[SiriusMsgRecipeRuntimeStatus] = None
    state: SiriusMsgHealthState


class SiriusMsgHealthComponent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    detail: Optional[SiriusMsgHealthComponentDetail] = None
    kind: SiriusMsgHealthComponentKind
    reason: str
    state: SiriusMsgHealthComponentState


class SiriusMsgHealthComponentDetail(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    adapterID: Optional[SiriusMsgAdapterID] = None
    adapterMode: Optional[SiriusMsgAdapterMode] = None
    adapterQueueMetrics: Optional[SiriusMsgAdapterQueueMetrics] = None
    adapterRunState: Optional[SiriusMsgAdapterRunState] = None
    endpoint: Optional[str] = None
    lastVMReachabilityProbeAt: Optional[float] = Field(
        None,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    peerCredentialPolicy: Optional[str] = None
    peerCredentialsEnforced: Optional[bool] = None
    port: Optional[conint(ge=0, le=65535)] = None
    tokenAgeDays: Optional[int] = None
    tokenCreatedAt: Optional[float] = Field(
        None,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    tokenStaleAfterDays: Optional[int] = None
    vmReachability: Optional[SiriusMsgVMReachabilityState] = None


class SiriusMsgHealthComponentKind(Enum):
    adapters = 'adapters'
    allowlistPersistence = 'allowlistPersistence'
    attachments = 'attachments'
    authToken = 'authToken'
    automation = 'automation'
    cursorPersistence = 'cursorPersistence'
    hooks = 'hooks'
    messagesDatabase = 'messagesDatabase'
    serviceLock = 'serviceLock'
    socket = 'socket'
    vmListener = 'vmListener'


class SiriusMsgHealthComponentState(Enum):
    blocked = 'blocked'
    degraded = 'degraded'
    healthy = 'healthy'
    notConfigured = 'notConfigured'


class SiriusMsgHealthState(Enum):
    blocked = 'blocked'
    degraded = 'degraded'
    healthy = 'healthy'
    starting = 'starting'
    stopped = 'stopped'


class SiriusMsgImageRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mimeType: Optional[str] = None
    sha256: Optional[str] = None
    url: AnyUrl


class SiriusMsgInboundEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: SiriusMsgInboundEventKind
    message: Optional[SiriusMsgMessageEvent] = None
    messageEdited: Optional[SiriusMsgMessageEditedEvent] = None
    messageUnsent: Optional[SiriusMsgMessageUnsentEvent] = None
    reaction: Optional[SiriusMsgReactionEvent] = None
    replyReference: Optional[SiriusMsgReplyReferenceEvent] = None


class SiriusMsgInboundEventKind(Enum):
    message = 'message'
    messageEdited = 'messageEdited'
    messageUnsent = 'messageUnsent'
    reaction = 'reaction'
    replyReference = 'replyReference'


class SiriusMsgMessageEditedEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    chatID: SiriusMsgChatID
    editedAt: float = Field(
        ...,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    isGroupChat: bool
    messageID: SiriusMsgMessageID
    rowID: conint(ge=0, le=9007199254740991) = Field(
        ...,
        description='Int64 ROWID constrained to the JavaScript safe-integer range for generated SDKs.',
    )


class SiriusMsgMessageEffectContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    effectName: str
    text: str


class SiriusMsgMessageEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attachments: list[SiriusMsgAttachmentMetadata]
    authorDisplayName: str
    chatID: SiriusMsgChatID
    handleID: Optional[SiriusMsgHandleID] = None
    id: SiriusMsgMessageID
    isGroupChat: bool
    receivedAt: float = Field(
        ...,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    replyToMessageID: Optional[SiriusMsgMessageID] = None
    rowID: conint(ge=0, le=9007199254740991) = Field(
        ...,
        description='Int64 ROWID constrained to the JavaScript safe-integer range for generated SDKs.',
    )
    text: str


class SiriusMsgMessageID(RootModel[str]):
    root: str = Field(..., description='Public message identifier.')


class SiriusMsgMessageUnsentEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    chatID: SiriusMsgChatID
    isGroupChat: bool
    messageID: SiriusMsgMessageID
    retractedAt: float = Field(
        ...,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    rowID: conint(ge=0, le=9007199254740991) = Field(
        ...,
        description='Int64 ROWID constrained to the JavaScript safe-integer range for generated SDKs.',
    )


class SiriusMsgOutboundAttachment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    byteCount: int
    displayName: Optional[str] = None
    fileURL: AnyUrl
    mimeType: str
    sha256: str


class SiriusMsgReaction(Enum):
    dislike = 'dislike'
    emphasize = 'emphasize'
    laugh = 'laugh'
    like = 'like'
    love = 'love'
    question = 'question'


class SiriusMsgReactionAction(Enum):
    added = 'added'
    removed = 'removed'


class SiriusMsgReactionContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action: SiriusMsgReactionAction
    reaction: SiriusMsgReaction
    targetMessageID: SiriusMsgMessageID


class SiriusMsgReactionEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action: SiriusMsgReactionAction
    authorDisplayName: str
    chatID: SiriusMsgChatID
    handleID: Optional[SiriusMsgHandleID] = None
    id: SiriusMsgMessageID
    isGroupChat: bool
    reaction: SiriusMsgReaction
    receivedAt: float = Field(
        ...,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    rowID: conint(ge=0, le=9007199254740991) = Field(
        ...,
        description='Int64 ROWID constrained to the JavaScript safe-integer range for generated SDKs.',
    )
    targetMessageID: SiriusMsgMessageID


class SiriusMsgRecipe(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    actions: list[SiriusMsgContent]
    description: str
    enabled: bool
    id: str
    integration: SiriusMsgRecipeIntegration
    name: str
    requiredCapabilities: list[SiriusMsgFeature]
    trigger: SiriusMsgRecipeTrigger


class SiriusMsgRecipeAdapterEnvelope(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    recipe: SiriusMsgRecipeIntegrationEnvelope
    triggerEvent: SiriusMsgRecipeTriggerEvent


class SiriusMsgRecipeIntegration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    identifier: Optional[str] = None
    kind: SiriusMsgRecipeIntegrationKind


class SiriusMsgRecipeIntegrationEnvelope(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    actionKinds: list[SiriusMsgContentKind]
    integration: SiriusMsgRecipeIntegration
    recipeID: str
    recipeName: str
    requiredCapabilities: list[SiriusMsgFeature]
    trigger: SiriusMsgRecipeTrigger


class SiriusMsgRecipeIntegrationKind(Enum):
    calendar = 'calendar'
    github = 'github'
    gmail = 'gmail'
    linear = 'linear'
    mcp = 'mcp'
    notion = 'notion'
    outlook = 'outlook'
    reminders = 'reminders'
    webhook = 'webhook'


class SiriusMsgRecipeRuntimeStatus(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    actionlessEnabledRecipeCount: int
    deferredTriggerRecipeCount: int
    diagnosticCounts: dict[str, int]
    enabledRecipeCount: int
    evaluatedCount: int
    failedCount: int
    lastEventAt: Optional[float] = Field(
        None,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    lastReloadAt: Optional[float] = Field(
        None,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    lastReloadDiagnostic: Optional[str] = None
    liveTriggers: list[SiriusMsgRecipeTrigger]
    loadedRecipeCount: int
    runningRecipeCount: int
    sentCount: int
    skippedCount: int
    triggerCounts: dict[str, SiriusMsgRecipeTriggerRuntimeCounts]


class SiriusMsgRecipeTrigger(Enum):
    edit = 'edit'
    inboundMessage = 'inboundMessage'
    reaction = 'reaction'
    schedule = 'schedule'
    unsend = 'unsend'
    webhook = 'webhook'


class SiriusMsgRecipeTriggerEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    chatID: SiriusMsgChatID
    handleID: Optional[SiriusMsgHandleID] = None
    isBridgeGenerated: bool
    messageID: Optional[SiriusMsgMessageID] = None
    rowID: Optional[conint(ge=0, le=9007199254740991)] = Field(
        None,
        description='Int64 ROWID constrained to the JavaScript safe-integer range for generated SDKs.',
    )
    source: SiriusMsgRecipeTriggerSource
    trigger: SiriusMsgRecipeTrigger


class SiriusMsgRecipeTriggerRuntimeCounts(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    diagnosticCounts: dict[str, int]
    evaluatedCount: int
    failedCount: int
    sentCount: int
    skippedCount: int


class SiriusMsgRecipeTriggerSource(Enum):
    inbound = 'inbound'
    schedule = 'schedule'
    webhook = 'webhook'


class SiriusMsgReconnectPolicy(Enum):
    default = 'default'
    none = 'none'


class SiriusMsgReplyContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    targetMessageID: SiriusMsgMessageID
    text: str


class SiriusMsgReplyReferenceEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    chatID: SiriusMsgChatID
    isGroupChat: bool
    messageID: SiriusMsgMessageID
    receivedAt: float = Field(
        ...,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    repliedToMessageID: SiriusMsgMessageID
    rowID: conint(ge=0, le=9007199254740991) = Field(
        ...,
        description='Int64 ROWID constrained to the JavaScript safe-integer range for generated SDKs.',
    )


class SiriusMsgRichLink(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    imageRef: Optional[SiriusMsgImageRef] = None
    kind: SiriusMsgRichLinkKind
    subtitle: Optional[str] = None
    title: Optional[str] = None
    url: AnyUrl


class SiriusMsgRichLinkCardArtifact(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    html: str
    publicURL: AnyUrl
    redirectStatusCode: int
    redirectURL: AnyUrl
    slug: str


class SiriusMsgRichLinkKind(Enum):
    generatedPreview = 'generatedPreview'
    plain = 'plain'


class SiriusMsgSchemaCapabilities(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    editAwarenessAvailable: bool
    replyReferenceAvailable: bool


class SiriusMsgSendConfirmationState(Enum):
    confirmed = 'confirmed'
    dispatched = 'dispatched'
    notRequested = 'notRequested'
    unconfirmed = 'unconfirmed'


class SiriusMsgSendRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    accountID: Optional[str] = None
    chatID: SiriusMsgChatID
    content: Optional[SiriusMsgContent] = None
    text: str


class SiriusMsgSendResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    accepted: bool
    confirmationState: SiriusMsgSendConfirmationState
    diagnosticCode: Optional[str] = None
    platformMessageID: Optional[str] = None
    resolvedContent: Optional[SiriusMsgContent] = None


class SiriusMsgServiceAck(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    chatID: SiriusMsgChatID
    messageID: SiriusMsgMessageID
    rowID: conint(ge=0, le=9007199254740991) = Field(
        ...,
        description='Int64 ROWID constrained to the JavaScript safe-integer range for generated SDKs.',
    )


class SiriusMsgServiceAuthToken(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    createdAt: float = Field(
        ...,
        description='Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.',
    )
    token: str


class SiriusMsgServiceError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: SiriusMsgServiceErrorCode
    diagnosticCode: Optional[str] = None
    message: str


class SiriusMsgServiceErrorCode(Enum):
    ackNotOutstanding = 'ackNotOutstanding'
    attachmentHashMismatch = 'attachmentHashMismatch'
    attachmentNotDelivered = 'attachmentNotDelivered'
    attachmentNotFound = 'attachmentNotFound'
    attachmentTooLarge = 'attachmentTooLarge'
    attachmentTransportUnsupported = 'attachmentTransportUnsupported'
    attachmentUnavailable = 'attachmentUnavailable'
    attachmentUnsupportedType = 'attachmentUnsupportedType'
    authFailed = 'authFailed'
    authRequired = 'authRequired'
    backpressure = 'backpressure'
    internalError = 'internalError'
    invalidRequest = 'invalidRequest'
    malformedFrame = 'malformedFrame'
    peerCredentialsRejected = 'peerCredentialsRejected'
    protocolVersionUnsupported = 'protocolVersionUnsupported'
    sendRejected = 'sendRejected'
    subscriptionAlreadyActive = 'subscriptionAlreadyActive'
    tokenRotationFailed = 'tokenRotationFailed'
    transportUnavailable = 'transportUnavailable'


class SiriusMsgServiceEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    health: Optional[SiriusMsgHealth] = None
    kind: SiriusMsgServiceEventKind
    message: Optional[SiriusMsgMessageEvent] = None
    messageEdited: Optional[SiriusMsgMessageEditedEvent] = None
    messageUnsent: Optional[SiriusMsgMessageUnsentEvent] = None
    reaction: Optional[SiriusMsgReactionEvent] = None
    replyReference: Optional[SiriusMsgReplyReferenceEvent] = None


class SiriusMsgServiceEventKind(Enum):
    health = 'health'
    message = 'message'
    messageEdited = 'messageEdited'
    messageUnsent = 'messageUnsent'
    reaction = 'reaction'
    replyReference = 'replyReference'


class SiriusMsgServiceRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ack: Optional[SiriusMsgServiceAck] = None
    allowlist: Optional[SiriusMsgAllowlist] = None
    attachmentFetch: Optional[SiriusMsgAttachmentFetchRequest] = None
    authToken: Optional[str] = None
    kind: SiriusMsgServiceRequestKind
    protocolVersion: Literal[1] = Field(..., description='SiriusMsg protocol version.')
    requestID: str
    sendRequest: Optional[SiriusMsgSendRequest] = None
    subscriptionOptions: Optional[SiriusMsgSubscriptionOptions] = None
    transport: Optional[SiriusMsgTransport] = None


class SiriusMsgServiceRequestKind(Enum):
    ack = 'ack'
    authenticate = 'authenticate'
    capabilities = 'capabilities'
    fetchAttachment = 'fetchAttachment'
    health = 'health'
    rotateAuthToken = 'rotateAuthToken'
    send = 'send'
    subscribe = 'subscribe'
    updateAllowlist = 'updateAllowlist'


class SiriusMsgServiceResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attachmentFile: Optional[SiriusMsgAttachmentFileReference] = None
    authTokenRotationResult: Optional[SiriusMsgAuthTokenRotationResult] = None
    capabilities: Optional[list[SiriusMsgCapability]] = None
    error: Optional[SiriusMsgServiceError] = None
    event: Optional[SiriusMsgServiceEvent] = None
    health: Optional[SiriusMsgHealth] = None
    kind: SiriusMsgServiceResponseKind
    protocolVersion: Literal[1] = Field(..., description='SiriusMsg protocol version.')
    requestID: Optional[str] = None
    sendResult: Optional[SiriusMsgSendResult] = None


class SiriusMsgServiceResponseKind(Enum):
    acked = 'acked'
    allowlistUpdated = 'allowlistUpdated'
    attachmentFile = 'attachmentFile'
    authTokenRotated = 'authTokenRotated'
    authenticated = 'authenticated'
    capabilities = 'capabilities'
    error = 'error'
    event = 'event'
    health = 'health'
    sendResult = 'sendResult'
    subscribed = 'subscribed'


class SiriusMsgSubscriptionOptions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    supportsAttachments: bool


class SiriusMsgTransport(Enum):
    localMessagesAutomation = 'localMessagesAutomation'
    managedRelay = 'managedRelay'
    messagesForBusiness = 'messagesForBusiness'


class SiriusMsgTransportDescriptor(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    displayName: str
    summary: str
    transport: SiriusMsgTransport
    trustPosture: SiriusMsgTransportTrustPosture


class SiriusMsgTransportTrustPosture(Enum):
    appleBusinessProvider = 'appleBusinessProvider'
    localMacPrivate = 'localMacPrivate'
    managedDedicatedRelay = 'managedDedicatedRelay'


class SiriusMsgTypingState(Enum):
    started = 'started'
    stopped = 'stopped'


class SiriusMsgUnsendContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    targetMessageID: SiriusMsgMessageID


class SiriusMsgUnsupportedContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    diagnosticCode: str
    feature: SiriusMsgFeature
    reason: str


class SiriusMsgVMReachabilityState(Enum):
    reachable = 'reachable'
    unprobed = 'unprobed'
    unreachable = 'unreachable'


class SiriusmsgProtocolV1(BaseModel):
    pass
