/* GENERATED by Scripts/generate-sdks.sh from Schema/siriusmsg-protocol-v1.schema.json. Do not edit. */

/**
 * Adapter identifier.
 *
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgAdapterID".
 */
export type SiriusMsgAdapterID = string;
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgAdapterMode".
 */
export type SiriusMsgAdapterMode = "direct" | "durable";
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgAdapterRunState".
 */
export type SiriusMsgAdapterRunState =
  | "backingOff"
  | "blocked"
  | "connecting"
  | "failed"
  | "idle"
  | "processing"
  | "stopped"
  | "subscribed";
/**
 * Public chat identifier.
 *
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgChatID".
 */
export type SiriusMsgChatID = string;
/**
 * Public handle identifier.
 *
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgHandleID".
 */
export type SiriusMsgHandleID = string;
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgAttachmentDiagnosticCode".
 */
export type SiriusMsgAttachmentDiagnosticCode =
  | "attachmentCapableSubscriberRequired"
  | "failedTranscode"
  | "sourceOutsideMessagesAttachments"
  | "tooLarge"
  | "unreadable"
  | "unsupportedType";
/**
 * Public attachment identifier.
 *
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgAttachmentID".
 */
export type SiriusMsgAttachmentID = string;
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgAttachmentKind".
 */
export type SiriusMsgAttachmentKind = "document" | "image";
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgAttachmentState".
 */
export type SiriusMsgAttachmentState = "failed" | "materialized" | "tooLarge" | "unreadable" | "unsupportedType";
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgFeature".
 */
export type SiriusMsgFeature =
  | "applePayBusinessAction"
  | "inboundAttachment"
  | "inboundEdit"
  | "inboundReaction"
  | "inboundReplyReference"
  | "inboundText"
  | "inboundUnsend"
  | "miniAppCard"
  | "sendEdit"
  | "sendFile"
  | "sendMessageEffect"
  | "sendReaction"
  | "sendRichLink"
  | "sendText"
  | "sendThreadedReply"
  | "sendTypingIndicator"
  | "sendUnsend";
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgCapabilityProof".
 */
export type SiriusMsgCapabilityProof =
  | "documented"
  | "none"
  | "providerDocumented"
  | "scriptingBridgeVerb"
  | "scriptingBridgeVerbAndDocumented"
  | "scriptingBridgeVerbAndStoreConfirmed"
  | "storeConfirmed";
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgCapabilitySupport".
 */
export type SiriusMsgCapabilitySupport =
  | "blocked"
  | "degraded"
  | "providerOnly"
  | "receiveOnly"
  | "researchGated"
  | "supported"
  | "unsupported";
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgTransport".
 */
export type SiriusMsgTransport = "localMessagesAutomation" | "managedRelay" | "messagesForBusiness";
/**
 * Public message identifier.
 *
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgMessageID".
 */
export type SiriusMsgMessageID = string;
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgContentKind".
 */
export type SiriusMsgContentKind =
  | "attachment"
  | "edit"
  | "messageEffect"
  | "reaction"
  | "reply"
  | "richLink"
  | "text"
  | "typing"
  | "unsend"
  | "unsupported";
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgReactionAction".
 */
export type SiriusMsgReactionAction = "added" | "removed";
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgReaction".
 */
export type SiriusMsgReaction = "dislike" | "emphasize" | "laugh" | "like" | "love" | "question";
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgRichLinkKind".
 */
export type SiriusMsgRichLinkKind = "generatedPreview" | "plain";
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgTypingState".
 */
export type SiriusMsgTypingState = "started" | "stopped";
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgVMReachabilityState".
 */
export type SiriusMsgVMReachabilityState = "reachable" | "unprobed" | "unreachable";
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgHealthComponentKind".
 */
export type SiriusMsgHealthComponentKind =
  | "adapters"
  | "allowlistPersistence"
  | "attachments"
  | "authToken"
  | "automation"
  | "cursorPersistence"
  | "hooks"
  | "messagesDatabase"
  | "serviceLock"
  | "socket"
  | "vmListener";
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgHealthComponentState".
 */
export type SiriusMsgHealthComponentState = "blocked" | "degraded" | "healthy" | "notConfigured";
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgRecipeTrigger".
 */
export type SiriusMsgRecipeTrigger = "edit" | "inboundMessage" | "reaction" | "schedule" | "unsend" | "webhook";
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgHealthState".
 */
export type SiriusMsgHealthState = "blocked" | "degraded" | "healthy" | "starting" | "stopped";
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgInboundEventKind".
 */
export type SiriusMsgInboundEventKind = "message" | "messageEdited" | "messageUnsent" | "reaction" | "replyReference";
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgRecipeIntegrationKind".
 */
export type SiriusMsgRecipeIntegrationKind =
  | "calendar"
  | "github"
  | "gmail"
  | "linear"
  | "mcp"
  | "notion"
  | "outlook"
  | "reminders"
  | "webhook";
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgRecipeTriggerSource".
 */
export type SiriusMsgRecipeTriggerSource = "inbound" | "schedule" | "webhook";
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgReconnectPolicy".
 */
export type SiriusMsgReconnectPolicy = "default" | "none";
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgSendConfirmationState".
 */
export type SiriusMsgSendConfirmationState = "confirmed" | "dispatched" | "notRequested" | "unconfirmed";
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgServiceErrorCode".
 */
export type SiriusMsgServiceErrorCode =
  | "ackNotOutstanding"
  | "attachmentHashMismatch"
  | "attachmentNotDelivered"
  | "attachmentNotFound"
  | "attachmentTooLarge"
  | "attachmentTransportUnsupported"
  | "attachmentUnavailable"
  | "attachmentUnsupportedType"
  | "authFailed"
  | "authRequired"
  | "backpressure"
  | "internalError"
  | "invalidRequest"
  | "malformedFrame"
  | "peerCredentialsRejected"
  | "protocolVersionUnsupported"
  | "sendRejected"
  | "subscriptionAlreadyActive"
  | "tokenRotationFailed"
  | "transportUnavailable";
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgServiceEventKind".
 */
export type SiriusMsgServiceEventKind =
  | "health"
  | "message"
  | "messageEdited"
  | "messageUnsent"
  | "reaction"
  | "replyReference";
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgServiceRequestKind".
 */
export type SiriusMsgServiceRequestKind =
  | "ack"
  | "authenticate"
  | "capabilities"
  | "fetchAttachment"
  | "health"
  | "rotateAuthToken"
  | "send"
  | "subscribe"
  | "updateAllowlist";
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgServiceResponseKind".
 */
export type SiriusMsgServiceResponseKind =
  | "acked"
  | "allowlistUpdated"
  | "attachmentFile"
  | "authTokenRotated"
  | "authenticated"
  | "capabilities"
  | "error"
  | "event"
  | "health"
  | "sendResult"
  | "subscribed";
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgTransportTrustPosture".
 */
export type SiriusMsgTransportTrustPosture = "appleBusinessProvider" | "localMacPrivate" | "managedDedicatedRelay";

/**
 * Public SiriusMsg local-service protocol schema. Generated from Swift public wire types.
 */
export interface SiriusMsgProtocolV1 {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgAdapterQueueMetrics".
 */
export interface SiriusMsgAdapterQueueMetrics {
  blockedReview: number;
  deadLetter: number;
  failed: number;
  oldestPendingJobAgeSeconds?: number;
  processing: number;
  queued: number;
  retrying: number;
  succeeded: number;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgAllowlist".
 */
export interface SiriusMsgAllowlist {
  chatIDs: SiriusMsgChatID[];
  handleIDs: SiriusMsgHandleID[];
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgAttachmentFetchRequest".
 */
export interface SiriusMsgAttachmentFetchRequest {
  attachmentID: SiriusMsgAttachmentID;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgAttachmentFileReference".
 */
export interface SiriusMsgAttachmentFileReference {
  localFilePath: string;
  metadata: SiriusMsgAttachmentMetadata;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgAttachmentMetadata".
 */
export interface SiriusMsgAttachmentMetadata {
  byteCount: number;
  diagnosticCode?: SiriusMsgAttachmentDiagnosticCode;
  displayName?: string;
  height?: number;
  id: SiriusMsgAttachmentID;
  kind: SiriusMsgAttachmentKind;
  mimeType: string;
  sha256?: string;
  state: SiriusMsgAttachmentState;
  width?: number;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgAuthTokenRotationResult".
 */
export interface SiriusMsgAuthTokenRotationResult {
  /**
   * Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.
   */
  createdAt: number;
  /**
   * Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.
   */
  previousCreatedAt: number;
  /**
   * Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.
   */
  rotatedAt: number;
  staleAfterDays: number;
  token: string;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgCapability".
 */
export interface SiriusMsgCapability {
  diagnosticCode?: string;
  evidenceNote: string;
  evidenceURL?: string;
  feature: SiriusMsgFeature;
  proof: SiriusMsgCapabilityProof;
  support: SiriusMsgCapabilitySupport;
  transport: SiriusMsgTransport;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgContent".
 */
export interface SiriusMsgContent {
  attachment?: SiriusMsgOutboundAttachment;
  edit?: SiriusMsgEditContent;
  kind: SiriusMsgContentKind;
  messageEffect?: SiriusMsgMessageEffectContent;
  reaction?: SiriusMsgReactionContent;
  reply?: SiriusMsgReplyContent;
  richLink?: SiriusMsgRichLink;
  text?: string;
  typing?: SiriusMsgTypingState;
  unsend?: SiriusMsgUnsendContent;
  unsupported?: SiriusMsgUnsupportedContent;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgOutboundAttachment".
 */
export interface SiriusMsgOutboundAttachment {
  byteCount: number;
  displayName?: string;
  fileURL: string;
  mimeType: string;
  sha256: string;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgEditContent".
 */
export interface SiriusMsgEditContent {
  replacementText: string;
  targetMessageID: SiriusMsgMessageID;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgMessageEffectContent".
 */
export interface SiriusMsgMessageEffectContent {
  effectName: string;
  text: string;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgReactionContent".
 */
export interface SiriusMsgReactionContent {
  action: SiriusMsgReactionAction;
  reaction: SiriusMsgReaction;
  targetMessageID: SiriusMsgMessageID;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgReplyContent".
 */
export interface SiriusMsgReplyContent {
  targetMessageID: SiriusMsgMessageID;
  text: string;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgRichLink".
 */
export interface SiriusMsgRichLink {
  imageRef?: SiriusMsgImageRef;
  kind: SiriusMsgRichLinkKind;
  subtitle?: string;
  title?: string;
  url: string;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgImageRef".
 */
export interface SiriusMsgImageRef {
  mimeType?: string;
  sha256?: string;
  url: string;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgUnsendContent".
 */
export interface SiriusMsgUnsendContent {
  targetMessageID: SiriusMsgMessageID;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgUnsupportedContent".
 */
export interface SiriusMsgUnsupportedContent {
  diagnosticCode: string;
  feature: SiriusMsgFeature;
  reason: string;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgCursorState".
 */
export interface SiriusMsgCursorState {
  lastRowIDByChatID: {
    [k: string]: number;
  };
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgHealth".
 */
export interface SiriusMsgHealth {
  activeTransport: SiriusMsgTransport;
  capabilities: SiriusMsgCapability[];
  components: SiriusMsgHealthComponent[];
  reason: string;
  recipeRuntime?: SiriusMsgRecipeRuntimeStatus;
  state: SiriusMsgHealthState;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgHealthComponent".
 */
export interface SiriusMsgHealthComponent {
  detail?: SiriusMsgHealthComponentDetail;
  kind: SiriusMsgHealthComponentKind;
  reason: string;
  state: SiriusMsgHealthComponentState;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgHealthComponentDetail".
 */
export interface SiriusMsgHealthComponentDetail {
  adapterID?: SiriusMsgAdapterID;
  adapterMode?: SiriusMsgAdapterMode;
  adapterQueueMetrics?: SiriusMsgAdapterQueueMetrics;
  adapterRunState?: SiriusMsgAdapterRunState;
  endpoint?: string;
  /**
   * Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.
   */
  lastVMReachabilityProbeAt?: number;
  peerCredentialPolicy?: string;
  peerCredentialsEnforced?: boolean;
  port?: number;
  tokenAgeDays?: number;
  /**
   * Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.
   */
  tokenCreatedAt?: number;
  tokenStaleAfterDays?: number;
  vmReachability?: SiriusMsgVMReachabilityState;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgRecipeRuntimeStatus".
 */
export interface SiriusMsgRecipeRuntimeStatus {
  actionlessEnabledRecipeCount: number;
  deferredTriggerRecipeCount: number;
  diagnosticCounts: {
    [k: string]: number;
  };
  enabledRecipeCount: number;
  evaluatedCount: number;
  failedCount: number;
  /**
   * Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.
   */
  lastEventAt?: number;
  /**
   * Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.
   */
  lastReloadAt?: number;
  lastReloadDiagnostic?: string;
  liveTriggers: SiriusMsgRecipeTrigger[];
  loadedRecipeCount: number;
  runningRecipeCount: number;
  sentCount: number;
  skippedCount: number;
  triggerCounts: {
    [k: string]: SiriusMsgRecipeTriggerRuntimeCounts;
  };
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgRecipeTriggerRuntimeCounts".
 */
export interface SiriusMsgRecipeTriggerRuntimeCounts {
  diagnosticCounts: {
    [k: string]: number;
  };
  evaluatedCount: number;
  failedCount: number;
  sentCount: number;
  skippedCount: number;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgInboundEvent".
 */
export interface SiriusMsgInboundEvent {
  kind: SiriusMsgInboundEventKind;
  message?: SiriusMsgMessageEvent;
  messageEdited?: SiriusMsgMessageEditedEvent;
  messageUnsent?: SiriusMsgMessageUnsentEvent;
  reaction?: SiriusMsgReactionEvent;
  replyReference?: SiriusMsgReplyReferenceEvent;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgMessageEvent".
 */
export interface SiriusMsgMessageEvent {
  attachments: SiriusMsgAttachmentMetadata[];
  authorDisplayName: string;
  chatID: SiriusMsgChatID;
  handleID?: SiriusMsgHandleID;
  id: SiriusMsgMessageID;
  isGroupChat: boolean;
  /**
   * Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.
   */
  receivedAt: number;
  replyToMessageID?: SiriusMsgMessageID;
  /**
   * Int64 ROWID constrained to the JavaScript safe-integer range for generated SDKs.
   */
  rowID: number;
  text: string;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgMessageEditedEvent".
 */
export interface SiriusMsgMessageEditedEvent {
  chatID: SiriusMsgChatID;
  /**
   * Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.
   */
  editedAt: number;
  isGroupChat: boolean;
  messageID: SiriusMsgMessageID;
  /**
   * Int64 ROWID constrained to the JavaScript safe-integer range for generated SDKs.
   */
  rowID: number;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgMessageUnsentEvent".
 */
export interface SiriusMsgMessageUnsentEvent {
  chatID: SiriusMsgChatID;
  isGroupChat: boolean;
  messageID: SiriusMsgMessageID;
  /**
   * Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.
   */
  retractedAt: number;
  /**
   * Int64 ROWID constrained to the JavaScript safe-integer range for generated SDKs.
   */
  rowID: number;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgReactionEvent".
 */
export interface SiriusMsgReactionEvent {
  action: SiriusMsgReactionAction;
  authorDisplayName: string;
  chatID: SiriusMsgChatID;
  handleID?: SiriusMsgHandleID;
  id: SiriusMsgMessageID;
  isGroupChat: boolean;
  reaction: SiriusMsgReaction;
  /**
   * Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.
   */
  receivedAt: number;
  /**
   * Int64 ROWID constrained to the JavaScript safe-integer range for generated SDKs.
   */
  rowID: number;
  targetMessageID: SiriusMsgMessageID;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgReplyReferenceEvent".
 */
export interface SiriusMsgReplyReferenceEvent {
  chatID: SiriusMsgChatID;
  isGroupChat: boolean;
  messageID: SiriusMsgMessageID;
  /**
   * Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.
   */
  receivedAt: number;
  repliedToMessageID: SiriusMsgMessageID;
  /**
   * Int64 ROWID constrained to the JavaScript safe-integer range for generated SDKs.
   */
  rowID: number;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgRecipe".
 */
export interface SiriusMsgRecipe {
  actions: SiriusMsgContent[];
  description: string;
  enabled: boolean;
  id: string;
  integration: SiriusMsgRecipeIntegration;
  name: string;
  requiredCapabilities: SiriusMsgFeature[];
  trigger: SiriusMsgRecipeTrigger;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgRecipeIntegration".
 */
export interface SiriusMsgRecipeIntegration {
  identifier?: string;
  kind: SiriusMsgRecipeIntegrationKind;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgRecipeAdapterEnvelope".
 */
export interface SiriusMsgRecipeAdapterEnvelope {
  recipe: SiriusMsgRecipeIntegrationEnvelope;
  triggerEvent: SiriusMsgRecipeTriggerEvent;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgRecipeIntegrationEnvelope".
 */
export interface SiriusMsgRecipeIntegrationEnvelope {
  actionKinds: SiriusMsgContentKind[];
  integration: SiriusMsgRecipeIntegration;
  recipeID: string;
  recipeName: string;
  requiredCapabilities: SiriusMsgFeature[];
  trigger: SiriusMsgRecipeTrigger;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgRecipeTriggerEvent".
 */
export interface SiriusMsgRecipeTriggerEvent {
  chatID: SiriusMsgChatID;
  handleID?: SiriusMsgHandleID;
  isBridgeGenerated: boolean;
  messageID?: SiriusMsgMessageID;
  /**
   * Int64 ROWID constrained to the JavaScript safe-integer range for generated SDKs.
   */
  rowID?: number;
  source: SiriusMsgRecipeTriggerSource;
  trigger: SiriusMsgRecipeTrigger;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgRichLinkCardArtifact".
 */
export interface SiriusMsgRichLinkCardArtifact {
  html: string;
  publicURL: string;
  redirectStatusCode: number;
  redirectURL: string;
  slug: string;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgSchemaCapabilities".
 */
export interface SiriusMsgSchemaCapabilities {
  editAwarenessAvailable: boolean;
  replyReferenceAvailable: boolean;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgSendRequest".
 */
export interface SiriusMsgSendRequest {
  accountID?: string;
  chatID: SiriusMsgChatID;
  content?: SiriusMsgContent;
  text: string;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgSendResult".
 */
export interface SiriusMsgSendResult {
  accepted: boolean;
  confirmationState: SiriusMsgSendConfirmationState;
  diagnosticCode?: string;
  platformMessageID?: string;
  resolvedContent?: SiriusMsgContent;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgServiceAck".
 */
export interface SiriusMsgServiceAck {
  chatID: SiriusMsgChatID;
  messageID: SiriusMsgMessageID;
  /**
   * Int64 ROWID constrained to the JavaScript safe-integer range for generated SDKs.
   */
  rowID: number;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgServiceAuthToken".
 */
export interface SiriusMsgServiceAuthToken {
  /**
   * Swift JSONEncoder default Date encoding: seconds since 2001-01-01T00:00:00Z.
   */
  createdAt: number;
  token: string;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgServiceError".
 */
export interface SiriusMsgServiceError {
  code: SiriusMsgServiceErrorCode;
  diagnosticCode?: string;
  message: string;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgServiceEvent".
 */
export interface SiriusMsgServiceEvent {
  health?: SiriusMsgHealth;
  kind: SiriusMsgServiceEventKind;
  message?: SiriusMsgMessageEvent;
  messageEdited?: SiriusMsgMessageEditedEvent;
  messageUnsent?: SiriusMsgMessageUnsentEvent;
  reaction?: SiriusMsgReactionEvent;
  replyReference?: SiriusMsgReplyReferenceEvent;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgServiceRequest".
 */
export interface SiriusMsgServiceRequest {
  ack?: SiriusMsgServiceAck;
  allowlist?: SiriusMsgAllowlist;
  attachmentFetch?: SiriusMsgAttachmentFetchRequest;
  authToken?: string;
  kind: SiriusMsgServiceRequestKind;
  /**
   * SiriusMsg protocol version.
   */
  protocolVersion: 1;
  requestID: string;
  sendRequest?: SiriusMsgSendRequest;
  subscriptionOptions?: SiriusMsgSubscriptionOptions;
  transport?: SiriusMsgTransport;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgSubscriptionOptions".
 */
export interface SiriusMsgSubscriptionOptions {
  supportsAttachments: boolean;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgServiceResponse".
 */
export interface SiriusMsgServiceResponse {
  attachmentFile?: SiriusMsgAttachmentFileReference;
  authTokenRotationResult?: SiriusMsgAuthTokenRotationResult;
  capabilities?: SiriusMsgCapability[];
  error?: SiriusMsgServiceError;
  event?: SiriusMsgServiceEvent;
  health?: SiriusMsgHealth;
  kind: SiriusMsgServiceResponseKind;
  /**
   * SiriusMsg protocol version.
   */
  protocolVersion: 1;
  requestID?: string;
  sendResult?: SiriusMsgSendResult;
}
/**
 * This interface was referenced by `SiriusMsgProtocolV1`'s JSON-Schema
 * via the `definition` "SiriusMsgTransportDescriptor".
 */
export interface SiriusMsgTransportDescriptor {
  displayName: string;
  summary: string;
  transport: SiriusMsgTransport;
  trustPosture: SiriusMsgTransportTrustPosture;
}
